apiVersion: v1
kind: Secret
metadata:
  name: identity-jwt
  namespace: fcg
type: Opaque
stringData:
  Jwt__RsaPrivateKeyPem: |
    -----BEGIN PRIVATE KEY-----
    REPLACE_ME
    -----END PRIVATE KEY-----
  Jwt__KeyId: "fcg-identity-key-1"
