apiVersion: v1
kind: Secret
metadata:
  name: identity-secret
  namespace: fcg
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "REPLACE_ME"
  RabbitMq__Username: "REPLACE_ME"
  RabbitMq__Password: "REPLACE_ME"
  AdminSeed__DefaultPassword: "REPLACE_ME"
